### PR TITLE
Fixes + User Management Commands + Basic Sudoers System

### PR DESCRIPTION
**Pull request by OcelotWalrus**
## Summary

This PR adds some fixes:

- fixed some of the `ecosystem.json` file permissions and ownerships
- fixed the `self.is_dir()` function, which had some weird bug
- fix the prompt displaying the working directory in lowercases
- make so that when you're root, the `$` becomes a `#`
- update the su command so that you also specify the group of the target
- also update the su command so that it checks if the target user at the target group actually exists
- also update the su command to include a `--h` argument that returns a help page
- make the `self.filesystem` var `self.__filesystem`

This PR also adds some new systems:

- add basic work of a sudoers file
- add a new check when loading /bin/, to skip a module if it contains a 'with open(' statement

This PR adds new commands and new os/script functions:

- the `useradd` command
- the `userdel` command
- the `passwd` command
- new os functions:
  - `self.__pathos_bus_is_root()` # return a boolean that tells if the user is authenticated as root
  - `self.__pathos_bus_entry_exists()`  # check if an entry at `registry.json` exists
  - `self.__pathos_bus_add_entry()`  # add a new entry to the `registry.json`
  - `self.__pathos_bus_change_passwd()`  # change the password of a `registry.json` entry
  - `self.__pathos_bus_remove_entry()`  # remove an entry to the `registry.json`
  - `self.get_working_entry()`  # return the current user and group
  - `self.add_user_entry()` # script method to check if the user can add an entry to `registry.json`
  - `self.remove_user_entry()`  # script method to check if the user can remove an entry to `registry.json`
  - `self.change_password()`  # script method to check if the user can change the password an entry at `registry.json`

### CODE REVIEW

**Comment by OcelotWalrus** [comment]
Check commit [3b4c030](https://github.com/Monarchz3ro/Silver/pull/25/commits/3b4c030236fd73653a8dc0bc2c087cd314d332a4), I've added the useradd command.

**Comment by OcelotWalrus** [comment]
@Monarchz3ro , I've a request: should I add this line of code, so there isn't __pycache__ folders generating anymore? It's kinda weird and annoying that __pycache__ stuff get generated in the root folder.
```python
import sys

sys.dont_write_bytecode = True
```

**Comment by Monarchz3ro** [comment]
I'd rather not do that, because the cache is generated for a reason and speeds up the system, so I'd rather make the mockup simply ignore those files instead of not write them at all

**Comment by OcelotWalrus** [comment]
> I'd rather not do that, because the cache is generated for a reason and speeds up the system, so I'd rather make the mockup simply ignore those files instead of not write them at all

Okay!

**Comment by OcelotWalrus** [comment]
I'll add the userdel command and then this PR will be ready.

**Comment by OcelotWalrus** [comment]
I've added the passwd and userdel command! I've tested them in every case, but feel free to test them yourself!

**Comment by OcelotWalrus** [comment]
I've added the passwd and userdel command! I've tested them in every case, but feel free to test them yourself!

**Comment by OcelotWalrus** [comment]
The PR is ready for review @Monarchz3ro !

**Comment by Monarchz3ro** [comment]
Apologies, I've been busy with a few other aspects of the game (such as story and graphics), but I'll look at your PR

**Comment by Monarchz3ro** [comment]
Mismatch: `passwd.py` has the help text for `userdel`

**Comment by OcelotWalrus** [comment]
> Apologies, I've been busy with a few other aspects of the game (such as story and graphics), but I'll look at your PR

No worries.

> Mismatch: `passwd.py` has the help text for `userdel`

I'll change that soon.

**Comment by OcelotWalrus** [comment]
Just fixed it!

**Comment by OcelotWalrus** [comment]
just fixed @Monarchz3ro!

**Pull request merged**
